config/routes.rb
Rails.application.routes.draw do
  resources :animals
  resources :zoos do
    resources :animals
  end

  root 'zoos#index'

end

app/models/animal.rb
class Animal < ActiveRecord::Base
end

app/models/zoo.rb
class Zoo < ActiveRecord::Base
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :weight, :breed, :zoo_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/zoos_controller.rb
class ZoosController < ApplicationController
  before_action :set_zoo, only: [:show, :edit, :update, :destroy]

  # GET /zoos
  # GET /zoos.json
  def index
    @zoos = Zoo.all
  end

  # GET /zoos/1
  # GET /zoos/1.json
  def show
  end

  # GET /zoos/new
  def new
    @zoo = Zoo.new
  end

  # GET /zoos/1/edit
  def edit
  end

  # POST /zoos
  # POST /zoos.json
  def create
    @zoo = Zoo.new(zoo_params)

    respond_to do |format|
      if @zoo.save
        format.html { redirect_to @zoo, notice: 'Zoo was successfully created.' }
        format.json { render :show, status: :created, location: @zoo }
      else
        format.html { render :new }
        format.json { render json: @zoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zoos/1
  # PATCH/PUT /zoos/1.json
  def update
    respond_to do |format|
      if @zoo.update(zoo_params)
        format.html { redirect_to @zoo, notice: 'Zoo was successfully updated.' }
        format.json { render :show, status: :ok, location: @zoo }
      else
        format.html { render :edit }
        format.json { render json: @zoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zoos/1
  # DELETE /zoos/1.json
  def destroy
    @zoo.destroy
    respond_to do |format|
      format.html { redirect_to zoos_url, notice: 'Zoo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zoo
      @zoo = Zoo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zoo_params
      params.require(:zoo).permit(:name, :location, :address)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zoos_helper.rb
module ZoosHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :zoo_id %><br>
    <%= f.number_field :zoo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Animals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Breed</th>
      <th>Zoo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.weight %></td>
        <td><%= animal.breed %></td>
        <td><%= animal.zoo_id %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @animal.weight %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @animal.breed %>
</p>

<p>
  <strong>Zoo:</strong>
  <%= @animal.zoo_id %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zoos/_form.html.erb
<%= form_for(@zoo) do |f| %>
  <% if @zoo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zoo.errors.count, "error") %> prohibited this zoo from being saved:</h2>

      <ul>
      <% @zoo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zoos/edit.html.erb
<h1>Editing Zoo</h1>

<%= render 'form' %>

<%= link_to 'Show', @zoo %> |
<%= link_to 'Back', zoos_path %>

app/views/zoos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zoos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zoos.each do |zoo| %>
      <tr>
        <td><%= zoo.name %></td>
        <td><%= zoo.location %></td>
        <td><%= zoo.address %></td>
        <td><%= link_to 'Show', zoo %></td>
        <td><%= link_to 'Edit', edit_zoo_path(zoo) %></td>
        <td><%= link_to 'Destroy', zoo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zoo', new_zoo_path %>

app/views/zoos/new.html.erb
<h1>New Zoo</h1>

<%= render 'form' %>

<%= link_to 'Back', zoos_path %>

app/views/zoos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zoo.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @zoo.location %>
</p>

<p>
  <strong>Address:</strong>
  <%= @zoo.address %>
</p>

<p>
  Animals in this zoo:
</p>

<% @zoo.animals.each do |animal| %>

  <%= animal.name %>

<% end %>

<%= link_to 'Edit', edit_zoo_path(@zoo) %> |
<%= link_to 'Back', zoos_path %>